language: objective-c
osx_image: xcode7.2
env:
    - TEST_CONFIG="RELEASE"
    - TEST_CONFIG="PODS"
    - TEST_CONFIG="CARTHAGE"

before_install:
- brew update
- brew install carthage
install: true
script:
    - if [[ "$TEST_CONFIG" == "RELEASE" ]]; then script/cibuild SwiftCheck SwiftCheck-iOS ; fi
    - if [[ "$TEST_CONFIG" == "RELEASE" ]]; then xcodebuild test -scheme SwiftCheck-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 1080p' ; fi
    - if [[ "$TEST_CONFIG" == "CARTHAGE" ]]; then carthage build --no-skip-current; fi
    - if [[ "$TEST_CONFIG" == "PODS" ]]; then pod lib lint; fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1d781e1bcbabade5de35
    on_success: always
    on_failure: always
    on_start: always
